channels:
  - conda-forge
dependencies:
  - python 3.7
  - appmode
  - numpy
  - pandas
  - plotly
  - ipywidgets
  - ipykernel=5.1.4=py37h39e3cac_0
  - ipython=7.12.0=py37h5ca1d4c_0
  - ipython_genutils=0.2.0=py37_0
  - _ipyw_jlab_nb_ext_conf=0.1.0=py37_0
  - jupyter=1.0.0=py37_7
  - jupyter_client=5.3.4=py37_0
  - jupyter_console=6.1.0=py_0
  - jupyter_core=4.6.1=py37_0
  - jupyterlab=1.2.6=pyhf63ae98_0
  - jupyterlab_server=1.0.6=py_0
  - jupyter-server==0.1.1
  - jupyterlab-pygments==0.1.1
