channels:
  - conda-forge
dependencies:
  - python 3.7
  - appmode
  - numpy
  - pandas
  - plotly
  - ipywidgets
  - ipykernel=5.1.4=py37h39e3cac_0
  - ipython=7.12.0=py37h5ca1d4c_0
  - ipython_genutils=0.2.0=py37_0
  - _ipyw_jlab_nb_ext_conf=0.1.0=py37_0
  - jupyter=1.0.0=py37_7
